version: '2'
services:
  icdv_intranet-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/icdv_intranet/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=icdv_intranet
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
